baekjoon/1874_스택수열/src/Minju.java, swea/1244_최대상금/src/Minju.java, swea/2806_N-Queen/src/Minju.java, swea/5215_햄버거다이어트/src/Minju.java, swea/7853_오타/src/Minju.java
[BOJ - 1874 스택수열]
[SWEA - 1244 최대상금]
[SWEA - 2806 N-Queen]
[SWEA - 5215 햄버거 다이어트]
[SWEA - 7853 오타]
=> 1주차 스터디문제 5개 - 민주

baekjoon/1874_스택수열/src/지한얼.java, swea/1244_최대상금/src/지한얼.java, swea/2806_N-Queen/src/지한얼.java, swea/5215_햄버거다이어트/src/지한얼.java, swea/7853_오타/src/지한얼.java
=> 1Week Study

.gitignore
=> chore: gitignore 추가

README.md, baekjoon/1107_리모컨/src/seonghun.java, baekjoon/1132_합/src/seonghun.java, baekjoon/2644_촌수계산/src/seonghun.java, baekjoon/3190_뱀/src/seonghun.java, baekjoon/9251_LCS/src/seonghun.java
=> 2주차 문제풀이(김성훈)

baekjoon/1068_트리/src/dongwoo.java, baekjoon/14699_관악산등산/src/dongwoo.java, baekjoon/1780_종이의개수/src/dongwoo.java, baekjoon/2014_소수의곱/src/dongwoo.java, baekjoon/2470_두용액/src/dongwoo.java
너무 어려워
too hard 
这非常困难
Es muy difícil
Es ist sehr schwierig
難しすぎる
слишком медленно
=> 3주차 문제풀이(고동우)

baekjoon/1068_트리/src/seonghun.java, baekjoon/14699_관악산등산/src/seonghun.java, baekjoon/1780_종이의개수/src/seonghun.java, baekjoon/2014_소수의곱/src/seonghun.java, baekjoon/2470_두용액/src/seonghun.java
=> 3주차 문제풀이(김성훈)

baekjoon/1068_트리/src/지한얼트리.java, baekjoon/14699_관악산등산/src/지한얼관악산.java, baekjoon/1780_종이의개수/src/지한얼종이1780.java, baekjoon/2014_소수의곱/src/지한얼소수의곱.java, baekjoon/2470_두용액/src/지한얼두용액2470.java
[BOJ - 14699 관악산등산] 
[BOJ - 1068 트리] : 
[BOJ - 1780 종이의 개수] 너무 오래걸림
[BOJ - 2470 두 용액] 도움
[BOJ - 2014 소수의 곱] :  시초
=> 3주차 문제풀이(지한얼)

baekjoon/1068_트리/src/Minju.java, baekjoon/14699_관악산등산/src/Minju.java, baekjoon/1780_종이의개수/src/Minju.java, baekjoon/2014_소수의곱/src/Minju.java, baekjoon/2470_두용액/src/Minju.java
[BOJ - 14699 관악산등산] 
[BOJ - 1068 트리] : G
[BOJ - 1780 종이의 개수] 
[BOJ - 2470 두 용액]
[BOJ - 2014 소수의 곱] : G
*G: 구글의 힘을 빌렸다
=> 3주차 문제풀이(김민주)

baekjoon/1068_트리/src/HyeKyoung.java, baekjoon/14699_관악산등산/src/HyeKyoung.java, baekjoon/1780_종이의개수/src/HyeKyoung.java, baekjoon/2014_소수의곱/src/HyeKyoung.java, baekjoon/2470_두용액/src/HyeKyoung.java
=> 3주차 문제풀이(김혜경)

baekjoon/17404_RGB거리2/src/Seonghun.java, baekjoon/1747_소수&팰린드롬/src/Seonghun.java, baekjoon/1916_최소비용구하기/src/Seonghun.java, baekjoon/2805_나무자르기/src/Seonghun.java, baekjoon/2879_코딩은예쁘게/src/Seonghun.java
=> 4주차 문제풀이(김성훈)

baekjoon/17404_RGB거리2/src/dongwoo.java, baekjoon/1747_소수&팰린드롬/src/dongwoo.java, baekjoon/1916_최소비용구하기/src/dongwoo.java, baekjoon/2805_나무자르기/src/dongwoo.java, baekjoon/2879_코딩은예쁘게/src/dongwoo.java
=> 4주차 문제풀이(고동우)

baekjoon/17404_RGB거리2/src/Minju.java, baekjoon/1747_소수&팰린드롬/src/Minju.java, baekjoon/1916_최소비용구하기/src/Minju.java, baekjoon/2805_나무자르기/src/Minju.java, baekjoon/2879_코딩은예쁘게/src/Minju.java
=> 4주차 문제풀이(김민주)

baekjoon/17404_RGB거리2/src/HyeKyoung.java, baekjoon/1747_소수&팰린드롬/src/HyeKyoung.java, baekjoon/1916_최소비용구하기/src/HyeKyoung.java, baekjoon/2805_나무자르기/src/HyeKyoung.java, baekjoon/2879_코딩은예쁘게/src/HyeKyoung.java
=> 4주차 문제풀이(김혜경)

baekjoon/1107_리모컨/src/지한얼_1107.java, baekjoon/1132_합/src/지한얼1132.java, baekjoon/17404_RGB거리2/src/JIHANEOL.java, baekjoon/1747_소수&팰린드롬/src/JIHANEOL.java, baekjoon/1780_종이의개수/src/지한얼종이1780.java, baekjoon/1916_최소비용구하기/src/JIHANEOL.java, baekjoon/2805_나무자르기/src/JIHANEOL.java, baekjoon/2879_코딩은예쁘게/src/JIHANEOL.java
알지비2를 푸는데 알지비1이 풀린다? G
코딩은 예쁘게 G
최소비용 G
G : 구글
=> 4주차 문제풀이(지한얼)

baekjoon/10164_격자상의경로/src/Minju.java, baekjoon/1043_거짓말/src/Minju.java, baekjoon/17135_캐슬디펜스/src/Minju.java, baekjoon/2667_단지번호붙이기/src/Minju.java, programmers/양궁대회/src/양궁대회/Minju.java
[PRO - 양궁대회]
[BOJ - 2667 단지번호 붙이기]
[BOJ - 1043 거짓말] : G
[BOJ - 10164 격자상의 경로]
[BOJ - 17135 캐슬디펜스]
ㅇ ㅓ ㄹ ㅕ ㅇ ㅜ ㅓ
=> 5주차 문제풀이 (김민주)

baekjoon/10164_격자상의경로/src/JIHANEOL.java, baekjoon/1043_거짓말/src/JIHANEOL.java, baekjoon/17135_캐슬디펜스/src/JIHANEOL.java, baekjoon/2667_단지번호붙이기/src/JIHANEOL.java, programmers/양궁대회/src/JIHANEOL.java
[PRO - 양궁대회] 반례봤다 .
[BOJ - 2667 단지번호 붙이기]
[BOJ - 1043 거짓말] :  유니온, 파인드
[BOJ - 10164 격자상의 경로] 디피뭐여
[BOJ - 17135 캐슬디펜스] 반례봤다.
=> 5주차 문제풀이(지한얼)

baekjoon/10164_격자상의경로/src/HyeKyoung.java, baekjoon/1043_거짓말/src/HyeKyoung.java, baekjoon/17135_캐슬디펜스/src/HyeKyoung.java, baekjoon/2667_단지번호붙이기/src/HyeKyoung.java, programmers/양궁대회/src/양궁대회/HyeKyoung.java
=> 5주차 문제풀이(김혜경)

baekjoon/10830_행렬제곱/src/JIHANEOL.java, baekjoon/1700_멀티탭스케줄링/src/JIHANEOL.java, baekjoon/17069_파이프옮기기2/src/JIHANEOL.java, baekjoon/2565_전깃줄/src/JIHANEOL.java, baekjoon/7662_이중우선순위큐/src/JIHANEOL.java
[BOJ] 10830 행렬 제곱
[BOJ] 1700 멀티탭 스케줄링 (구글링) 코드가 더럽고 안풀린다..
[BOJ] 17069 파이프 옮기기2 (구글링)  디피란 무엇인가...
[BOJ] 2565 전깃줄
[BOJ] 7662 이중 우선순위 큐 (구글링) treemap을 사용하는 이유,,
중꺾마......
=> 6주차 문제풀이 (지한얼)

baekjoon/10830_행렬제곱/src/HyeKyoung.java, baekjoon/1700_멀티탭스케줄링/src/HyeKyoung.java, baekjoon/17069_파이프옮기기2/src/HyeKyoung.java, baekjoon/2565_전깃줄/src/HyeKyoung.java, baekjoon/7662_이중우선순위큐/src/HyeKyoung.java
=> 6주차 문제풀이(김혜경)

baekjoon/10830_행렬제곱/src/Minju.java, baekjoon/1700_멀티탭스케줄링/src/Minju.java, baekjoon/17069_파이프옮기기2/src/Minju.java, baekjoon/2565_전깃줄/src/Minju.java, baekjoon/7662_이중우선순위큐/src/Minju.java
=> 6주차 문제풀이 (김민주)

baekjoon/10775_공항/src/HyeKyoung.java, baekjoon/14719_빗물/src/HyeKyoung.java, baekjoon/2042_구간합구하기/src/HyeKyoung.java, baekjoon/2098_외판원순회/src/HyeKyoung.java
=> 7주차 문제풀이 (김혜경)

baekjoon/10775_공항/src/JIHANEOL.java, baekjoon/14502_연구소/src/JIHANEOL.java, baekjoon/14719_빗물/src/JIHANEOL.java, baekjoon/2042_구간합구하기/src/JIHANEOL.java, baekjoon/2098_외판원순회/src/JIHANEOL.java
=> 7주차 문제풀이 (지한얼)

baekjoon/10775_공항/src/Minju.java, baekjoon/14502_연구소/src/Minju.java, baekjoon/14719_빗물/src/Minju.java, baekjoon/2042_구간합구하기/src/Minju.java, baekjoon/2098_외판원순회/src/Minju.java
=> 7주차 문제풀이 (김민주)

README.md, baekjoon/10775_공항/src/Seonghun.java, baekjoon/14502_연구소/src/Seonghun.java, baekjoon/14719_빗물/src/Seonghun.java, baekjoon/2042_구간합구하기/src/Seonghun.java, baekjoon/2098_외판원순회/src/Seonghun.java
=> 7주차 문제풀이 (김성훈)

baekjoon/1261_알고스팟/src/JIHANEOL.java, baekjoon/12904_A와B/src/JIHANEOL.java, baekjoon/2206_벽부수고이동하기/src/JIHANEOL.java, baekjoon/2638_치즈/src/JIHANEOL.java, baekjoon/9077_지뢰제거/src/JIHANEOL.java
[문제풀이 : 12904.A와B 골드5]
[문제풀이 : 2638. 치즈 성훈이와 같은데 큐를 더써서 메모리가 터지나? 모르겄다]
[문제풀이: 1261. 알고스팟 0-1 bfs]
[문제풀이:2206.벽부수고이동하기 좋았다]
[문제풀이:9077.지뢰제거 왜 이런 생각을 못하죠]
=> 8주차 문제풀이 (지한얼)

baekjoon/1261_알고스팟/src/Hyekyoung.java, baekjoon/12904_A와B/src/Hyekyoung.java, baekjoon/2206_벽부수고이동하기/src/Hyekyoung.java, baekjoon/2638_치즈/src/Hyekyoung.java, baekjoon/9077_지뢰제거/src/Hyekyoung.java
=> 8주차 문제풀이 (김혜경)

baekjoon/1261_알고스팟/src/Minju.java, baekjoon/12904_A와B/src/Minju.java, baekjoon/2206_벽부수고이동하기/src/Minju.java, baekjoon/2638_치즈/src/Minju.java, baekjoon/9077_지뢰제거/src/Minju.java
=> 8주차 문제풀이 (김민주)

README.md, baekjoon/1261_알고스팟/src/Seonghun.java, baekjoon/12904_A와B/src/Seonghun.java, baekjoon/2206_벽부수고이동하기/src/Seonghun.java, baekjoon/2638_치즈/src/Seonghun.java, baekjoon/9077_지뢰제거/src/Seonghun.java
=> 8주차 문제풀이 (김성훈)

baekjoon/11726_2xn타일링/src/Seonghun.java, baekjoon/20437_문자열게임2/src/Seonghun.java, baekjoon/21317_징검다리건너기/src/Seonghun.java, baekjoon/2342_DanceDanceRevolution/src/Seonghun.java, baekjoon/7432_디스크트리/src/Seonghun.java, programmers/디스크컨트롤러/src/Seonghun.java
=> 9주차 문제풀이 (김성훈)

baekjoon/11726_2xn타일링/src/Minju.java, baekjoon/20437_문자열게임2/src/Main.java, baekjoon/21317_징검다리건너기/src/Minju.java, baekjoon/2342_DanceDanceRevolution/src/Minju.java, baekjoon/7432_디스크트리/src/Minju.java, programmers/디스크컨트롤러/src/Minju.java
=> 9주차 문제풀이 (김민주)

baekjoon/12015_가장긴증가하는부분수열2/src/JIHANEOL.java, baekjoon/19623_회의실배정4/src/JIHANEOL.java, baekjoon/20056_마법사상어와파이어볼/src/JIHANEOL.java, baekjoon/9935_문자열폭발/src/JIHANEOL.java, programmers/가사검색/src/JIHANEOL.java, programmers/가사검색/src/JIHANEOL2.java, programmers/가사검색/src/pactice.java, programmers/기지국설치/src/JIHANEOL.java
=> 10주차 문제풀이 (지한얼)

baekjoon/12015_가장긴증가하는부분수열2/src/Hyekyoung.java, baekjoon/20056_마법사상어와파이어볼/src/Hyekyoung.java, baekjoon/9935_문자열폭발/src/Hyekyoung.java, programmers/가사검색/src/Hyekyoung.java, programmers/기지국설치/src/Hyekyoung.java
=> 10주차 문제풀이 (김혜경)

baekjoon/1162_도로포장/src/JIHANEOL.java, baekjoon/11657_타임머신/src/JIHANEOL.java, baekjoon/18405_경쟁적전염/src/JIHANEOL.java, baekjoon/1956_운동/src/JIHANEOL.java, swea/2382_미생물격리/src/JIHANEOL.java, swea/4193_수영대회결승전/src/JIHANEOL.java
=> 11주차 문제풀이 (지한얼)

baekjoon/1162_도로포장/src/Minju.java, baekjoon/11657_타임머신/src/Minju.java, baekjoon/18405_경쟁적전염/src/Minju.java, baekjoon/1956_운동/src/Minju.java, swea/2382_미생물격리/src/Minju.java, swea/4193_수영대회결승전/src/Minju.java
=> 11주차 문제풀이 (김민주)

baekjoon/1379_강의실2/src/JIHANEOL.java, baekjoon/14698_전생했더니슬라임연구자였던건에대하여(Hard)/src/JIHANEOL.java, baekjoon/1863_스카이라인쉬운거/src/JIHANEOL.java, baekjoon/2056_작업/src/JIHANEOL.java, baekjoon/2812_크게만들기/src/JIHANEOL.java, programmers/베스트앨범/src/JIHANEOL.java
스카이라인 - 문제 이해가 안된다...
강의실2 - 왜 틀린지 모르겄다...
=> 12주차 문제풀이 (지한얼)

baekjoon/1379_강의실2/src/Minju.java, baekjoon/14698_전생했더니슬라임연구자였던건에대하여(Hard)/src/Minju.java, baekjoon/1863_스카이라인쉬운거/src/Minju.java, baekjoon/2056_작업/src/Minju.java, baekjoon/2812_크게만들기/src/Minju.java, programmers/베스트앨범/src/Minju.java
=> 12주차 문제풀이 (김민주)

baekjoon/1379_강의실2/src/Hyekyoung.java, baekjoon/14698_전생했더니슬라임연구자였던건에대하여(Hard)/src/Hyekyoung.java, baekjoon/1863_스카이라인쉬운거/src/Hyekyoung.java, baekjoon/2056_작업/src/Hyekyoung.java, baekjoon/2812_크게만들기/src/Hyekyoung.java, programmers/베스트앨범/src/Hyekyoung.java
=> 12주차 문제풀이 (김혜경)

baekjoon/1379_강의실2/src/Seonghun.java, baekjoon/14698_전생했더니슬라임연구자였던건에대하여(Hard)/src/Seonghun.java, baekjoon/1863_스카이라인쉬운거/src/Seonghun.java, baekjoon/2056_작업/src/Seonghun.java, baekjoon/2812_크게만들기/src/Seonghun.java, programmers/베스트앨범/src/Seonghun.java
=> 12주차 문제풀이 (김성훈)
